-- Shared item data. Both the server and HUD read this module.
return {
	Fists = {
		DisplayName = "Fists",
		Price = 0,
		Color = Color3.fromRGB(224, 184, 144),
		Kind = "Melee",
		Damage = 10,
		ComboDamage = {10, 12, 18},
		Cooldown = 0.38,
		ComboReset = 1.1,
		Range = 4.2,
		HeavyKnockback = 28,
		Permanent = true,
	},
	Bat = {
		DisplayName = "Baseball Bat",
		Price = 150,
		Color = Color3.fromRGB(121, 85, 58),
		Kind = "Melee",
		Damage = 35,
		Cooldown = 0.7,
		Range = 5.5,
	},
	Pistol = {
		DisplayName = "9mm Pistol",
		Price = 500,
		Color = Color3.fromRGB(45, 48, 55),
		Kind = "Gun",
		Damage = 26,
		Cooldown = 0.28,
		Range = 250,
		MagazineSize = 12,
		AmmoItem = "PistolAmmo",
		StarterAmmo = 36,
		ReloadTime = 1.45,
		HeadshotMultiplier = 1.65,
		Recoil = 1.25,
		Pellets = 1,
		Spread = 0,
	},
	PistolAmmo = {
		DisplayName = "9mm Ammunition",
		Price = 60,
		Color = Color3.fromRGB(190, 159, 75),
		Kind = "Ammo",
		Bundle = 24,
	},
	Shotgun = {
		DisplayName = "Pump Shotgun",
		Price = 950,
		Color = Color3.fromRGB(74, 59, 48),
		Kind = "Gun",
		Damage = 10,
		Cooldown = 0.9,
		Range = 130,
		MagazineSize = 6,
		AmmoItem = "Shells",
		StarterAmmo = 18,
		ReloadTime = 2.1,
		HeadshotMultiplier = 1.35,
		Recoil = 3.4,
		Pellets = 8,
		Spread = 0.065,
	},
	Shells = {
		DisplayName = "12-Gauge Shells",
		Price = 90,
		Color = Color3.fromRGB(174, 48, 44),
		Kind = "Ammo",
		Bundle = 12,
	},
	Medkit = {
		DisplayName = "Medkit",
		Price = 100,
		Color = Color3.fromRGB(205, 48, 48),
		Kind = "Consumable",
		Heal = 45,
		Cooldown = 1.0,
	},
	Balloon = {
		DisplayName = "Lift Balloon",
		Price = 200,
		Color = Color3.fromRGB(235, 72, 92),
		Kind = "Utility",
		JumpPower = 82,
		JumpHeight = 13,
	},
}
